#!/bin/sh
# Block commits that carry secrets. Install with:
#   ln -sf ../../scripts/pre-commit .git/hooks/pre-commit
exec python3 "$(git rev-parse --show-toplevel)/scripts/check_secrets.py" --staged
